-- Create groupposts table for admin instructions
CREATE TABLE IF NOT EXISTS groupposts (
  postId INT AUTO_INCREMENT PRIMARY KEY,
  groupId INT NOT NULL,
  adminId INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (groupId) REFERENCES `groups`(groupId) ON DELETE CASCADE,
  FOREIGN KEY (adminId) REFERENCES users(userId) ON DELETE CASCADE
);
